concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  test:
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build all without tests
      run: mvn clean install -DskipTests -B --file pom.xml
    - continue-on-error: true
      name: Run tests
      run: mvn test -B --file pom.xml
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        - 20
        - 21-ea
        os:
        - ubuntu-22.04
        - windows-2022
        - macos-11
name: JOL Pre-Integration Tests
on:
  repository_dispatch:
    types: trigger-ga___pre-integration.yml
